/*
    MODEL: PROJECT.
    CONTAINS DEFAULT SCHEMA STRUCTURE FOR PROJECT MODEL
*/

'use strict'
var mongoose =  require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');

var Schema = mongoose.Schema;
var ProjectSchema = Schema({
    name: {type:String,required:[true,'Please put the name of the project']}, //NAME OF THE PROJECT (CAN'T BE NULL)
    createdAt: {type:Date,default:Date.now}, //WHEN WAS CREATED THE PROJECT (AUTOGENERATED)
    owner: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true,'Please asign the user id']
    } //REF TO USER (REQUIRES USER ID)
});


ProjectSchema.plugin(uniqueValidator);
module.exports = mongoose.model('Project', ProjectSchema);