/*
    MODEL: TASK.
    CONTAINS DEFAULT SCHEMA STRUCTURE FOR TASK MODEL
*/


'use strict'
var mongoose =  require('mongoose');
const idValidator = require('mongoose-id-validator');

var Schema = mongoose.Schema;
var TaskSchema = Schema({
    name: {type:String,default: null}, //CAN BE NULL IF NAME ISN'T SPECIFIED
    duration: {type:Number,default:0}, //DURATION OF THE TASK IN SECONDS
    last_start: {type:Date,default:Date.now}, //LAST TIME STARTED
    paused: {type:Date,default:null}, //IF TASK IS PAUSED, RUNNING OR NEVER STARTED
    createdAt: {type:Date,default:Date.now}, //WHEN WAS CREATED THE TASK (AUTOGENERATED)
    status: {type:Boolean,default:false}, //TWO STATES true = Running, false = Stopped, 
    owner: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true,'Please assign the user id']
    },//REF TO USER (REQUIRES USER ID)
    project:{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Project',
        default: null
    } //CAN HAVE A PROJECT OR NOT
});

TaskSchema.plugin(idValidator);

module.exports = mongoose.model('Task', TaskSchema);